### ISSUE TITLE
Tableau Desktop - 

### ISSUE THREAD

**Issue by patgmac** [autopkg/jss-recipes#119]
When running the Tableau Desktop recipe, I'm getting the error "JSSImporter requires missing argument version". 

Running the parent pkg recipe does seem to have a %version% variable. 

<img width="532" alt="jssimporter" src="https://cloud.githubusercontent.com/assets/614564/25444446/2b512c70-2a79-11e7-82f5-201207170ad4.png">

**Comment by homebysix** [comment]
Hi @patgmac — Can you try switching to the `tableau-desktop-version-key` branch and running again? This commit might fix what you're seeing: https://github.com/autopkg/jss-recipes/commit/097d546f3ec302eeea14c8837353c0b800fe0b7e

**Comment by homebysix** [comment]
Merged #138.
