### ISSUE TITLE
Parallels Desktop.jss

### ISSUE THREAD

**Issue by RossDD** [autopkg/jss-recipes#123]
Hello, 

parallels desktop.pkg that get's created results in a corrupt install. Parallels Application appears but when you try to open it, Parallels spits out a 15431 error (seems generic) and the 'solution' just takes you to parallels support site.

This is occurring regardless of deployment method, happens when manually installing as well. I had a quick check on #AutoPkg Slack Channel and a few folks last year mentioned this issue as well so doesn't look to be specific to this version. 

If I install via pd12.dmg from Parallels site and install all is OK.

**Comment by homebysix** [comment]
Root cause is probably here: https://github.com/autopkg/homebysix-recipes/issues/120
