### ISSUE TITLE
The Microsoft patch recipes have OS Requirements that do not include 10.13.x...

### ISSUE THREAD

**Issue by everetteallen** [autopkg/jss-recipes#130]
The recipes for the Microsoft office patches at OS Requirements that do not include 10.13.x and in fact the last update a year ago was to add 10.12.x..
Microsoft Excel	Add 10.12.x to OS REQUIREMENTS	a year ago
Microsoft OneNote	Add 10.12.x to OS REQUIREMENTS	a year ago
Microsoft Outlook	Add 10.12.x to OS REQUIREMENTS	a year ago
Microsoft PowerPoint	Add 10.12.x to OS REQUIREMENTS	a year ago
Microsoft Remote Desktop	updated OS_REQUIREMENTS for macOS Sierra support, updated 
Microsoft Word	Add 10.12.x to OS REQUIREMENTS	a year ago
I would be great to get these updated to support macOS High Sierra.

**Comment by homebysix** [comment]
@everetteallen - Great idea! I submitted PR #132 for that change. Can you give the modified recipes a try-out?

Also, keep in mind that you can always change the OS_REQUIREMENTS value in your own override without waiting for us to update jss-recipes. (You probably already did that.)
