### ISSUE TITLE
iTerm2 - <key>JSS_INVENTORY_NAME</key>

### ISSUE THREAD

**Issue by catpele** [autopkg/jss-recipes#143]
Hi,

Can anybody verify the below and update the recipe, please?

The `<key>JSS_INVENTORY_NAME</key>` string needs to be updated to `<string>iTerm.app</string>` in order to register the installed iTerm.app, otherwise we get no computers in the group and therefore no auto updates.

Tested with a local override and it works.

Using Jamf Pro 10, although I suspect the behaviour would be the same on any version of JSS.

Thanks

**Comment by catpele** [comment]
Created a pull request with required change.

**Comment by homebysix** [comment]
Closed by #144. Thanks!
