### ISSUE TITLE
GoToMeeting Update-smart group does not properly populate app comparison

### ISSUE THREAD

**Issue by Yohan460** [autopkg/jss-recipes#145]
When a new update-smart group is created at times where a new version is available it looks for a GoToMeeting.app file instead of the proper GoToMeeting (8034).app which would correspond to the version 8.18.0.8034.

**Comment by homebysix** [comment]
Closing issue due to [repo deprecation and archive](https://github.com/autopkg/jss-recipes/issues/267).
