### ISSUE TITLE
Citrix Receiver is being re-branded as Citrix Workspace

### ISSUE THREAD

**Issue by smashism** [autopkg/jss-recipes#164]
Just kind of an FYI, I'm unsure what the impact will be on how the jss recipe and the parent recipes will be impacted. Citrix is rebranding Receiver as Workspace, and will stop updating Receiver. Unsure on timeline. Workspace is already available.

https://www.citrix.com/products/citrix-workspace/

**Comment by homebysix** [comment]
Closing issue due to [repo deprecation and archive](https://github.com/autopkg/jss-recipes/issues/267).
