### ISSUE TITLE
Recipes failing or asking to search github

### ISSUE THREAD

**Issue by sharrist** [autopkg/jss-recipes#183]
Good morning,

I'm trying to make a zoom pkg and policy using autopkg run Zoom.jss and it fails every time with an unarchiver error.  I tried two other recipes (Wireshark and Textmate) just to see if it was the zoom recipe and it says that they don't even exist.

**Comment by sharrist** [comment]
`Error in com.github.jss-recipes.jss.Zoom: Processor: Unarchiver: Error: Unarchiving /Users/username/Library/AutoPkg/Cache/com.github.jss-recipes.jss.Zoom/expanded/Scripts/7zr.zip with ditto failed: ditto: /Users/username/Library/AutoPkg/Cache/com.github.jss-recipes.jss.Zoom/expanded/Scripts/7zr.zip: No such file or directory` 

This is the error I'm getting.

**Comment by homebysix** [comment]
Hi @sharrist - Looks like you got this fixed after discussing in Slack?

**Comment by sharrist** [comment]
Yes I did thanks so much for getting back to me.
