### ISSUE TITLE
PyCharm Complains about several layers of Parent Recipes

### ISSUE THREAD

**Issue by HewittJC** [autopkg/jss-recipes#188]
I get the following error when trying to use the PyCharm Recipe even though I have the parent. It appears there is yet another missing parent, though I cannot find where said parent even exists.

![image](https://user-images.githubusercontent.com/28607855/63364986-aaaa7100-c344-11e9-96ff-9e5637771c2f.png)

**Comment by homebysix** [comment]
Hi @HewittJC - The [PyCharm.jss recipe's](https://github.com/autopkg/jss-recipes/blob/master/PyCharm/PyCharm.jss.recipe#L34-L35) parent is com.github.chilcote.pkg.PyCharm, and [that recipe's](https://github.com/autopkg/chilcote-recipes/blob/master/JetBrains/PyCharm.pkg.recipe#L14-L15) parent is com.github.mosen.download.PyCharmPro. So you'll need both the chilcote-recipes and mosen-recipes repositories added, if you haven't already.

```
autopkg repo-add chilcote-recipes mosen-recipes
```

Then try the PyCharm.jss recipe again and see if you get different results.

**Comment by homebysix** [comment]
Closing due to no response, but please reopen with details if the issue continues.
