### ISSUE TITLE
Documentation clarification for parent recipes...

### ISSUE THREAD

**Issue by everetteallen** [autopkg/jss-recipes#19]
So the documentation (i.e. README.md) says:
"JSS recipes use PKG recipes as parents." However I see like for yo.jss
` <key>ParentRecipe</key>`
`        <string>com.github.sheagcraig.download.yo</string>`
Maybe the docs should say:
Jss recipes use parent recipes that produce PKG installers. 
Since the intent is:
"This ensures that a standard Apple package (pkg) file can be uploaded to the distribution points."
I don't think the idea was to force JSS recipes to use PKG recipes but if so then the issue need to be moved to the yo.jss :-).

**Comment by sheagcraig** [comment]
You are correct. The original intention was to always use a package parent recipe; however, once we started getting into cases like yo where there is a package already built and ready to download, that it seemed silly to make a pkg recipe that did nothing. I'll update this.
