### ISSUE TITLE
Error running recipes com.github.github.jss-recipes.OracleJava8.jss

### ISSUE THREAD

**Issue by HasanSert** [autopkg/jss-recipes#206]
Hello,

Each times that we want to run the OracleJava8 recipe, we got this error message : 

No match found on URL: https://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html
Failed.

Could you please help us by fixing this issue ?

Thanks,

Hasan

**Comment by homebysix** [comment]
This issue is not related to the JSS recipe. I suspect it's the download recipe which is failing.
