### ISSUE TITLE
Update Google Chrome.jss to point at new Google provided PKG

### ISSUE THREAD

**Issue by staze** [autopkg/jss-recipes#208]
Hi there,

I'm trying to make my own override for the Google Chrome.jss to point at the Chrome pkg that google now provides, but it's not working (doesn't upload to my DP). Was wondering if we could get an updated .jss. 

Thanks!

**Comment by homebysix** [comment]
Hi @staze - You might try overriding this recipe instead: https://github.com/autopkg/rtrouton-recipes/blob/master/JSS/GoogleChromeEnterprise.jss.recipe

**Comment by staze** [comment]
> Hi @staze - You might try overriding this recipe instead: https://github.com/autopkg/rtrouton-recipes/blob/master/JSS/GoogleChromeEnterprise.jss.recipe

Bam, thank you! I didn't even notice that one. =)
