### ISSUE TITLE
Google Earth Pro.jss.recipe Error

### ISSUE THREAD

**Issue by killer23d** [autopkg/jss-recipes#209]
Looks like there is a code change and caused the error:

Error in local.jss.Google Earth Pro: Processor: CodeSignatureVerifier: Error: Mismatch in authority names. Note that all verification can be disabled by setting the variable DISABLE_CODE_SIGNATURE_VERIFICATION to a non-empty value.

Repo were updated and Trust Info updated for Overrides already.

**Comment by homebysix** [comment]
Hi @killer23d - JSS recipes don't contain code signature verification information. The parent recipe might contain the string that needs updating: https://github.com/autopkg/nmcspadden-recipes/blob/master/GoogleEarthPro/GoogleEarthPro.download.recipe#L37

However, I'm also open to a PR that changes the parent recipe to nstrauss's, per https://github.com/autopkg/nmcspadden-recipes/issues/36.
