### ISSUE TITLE
com.github.jss-recipes.jss.depnotify Glob Failed

### ISSUE THREAD

**Issue by ladygreyjedi** [autopkg/jss-recipes#211]
Since upgrading to Python3, com.github.jss-recipes.jss.depnotify fails with Error processing path "~/Library/Autopkg/Cache/local.jss.DEPNotify/DEPNotify/Applications/Utilities/DEPNotify.app failed to Glob." 

It looks like when it downloads the zip, it doesn't extract or build the DEPNotify.app.

**Comment by homebysix** [comment]
Does running the parent (pkg) recipe result in a similar error? If so, the problem is likely [this one](https://github.com/autopkg/rderewianko-recipes/issues/7).
