### ISSUE TITLE
TheUrachiver missing argument

### ISSUE THREAD

**Issue by tsinghzf** [autopkg/jss-recipes#212]
The following recipes failed:
    The Unarchiver.jss.recipe
        JSSImporter requires missing argument pkg_path

I am getting the error above when using autopkg to push a new update, please check and resolve

**Comment by homebysix** [comment]
Hi @tsinghzf - Could you `autopkg repo-update jss-recipes` and try again now?

**Comment by tsinghzf** [comment]
I have received the same error

**Comment by homebysix** [comment]
Could you share the verbose output of your `autopkg run` so I could try to reproduce it? Thank you.

**Comment by homebysix** [comment]
Closing due to no response, but please reopen with verbose output if the issue continues.
