### ISSUE TITLE
Zoom processing error

### ISSUE THREAD

**Issue by dwshore-personal** [autopkg/jss-recipes#215]
When I try to run the latest zoom recipe I get the following error:
`Processor: JSSImporter: Error: 'utf-8' codec can't decode byte 0xc8 in position 24: invalid continuation byte`

**Comment by homebysix** [comment]
Could you try again, making sure your Zoom recipe related repos are up to date, latest version of AutoPkg and JSSImporter?

What you're encountering looks like a mismatch between Python 2 and Python 3, perhaps because one of the tools in the chain is not updated.
