### ISSUE TITLE
Microsoft PowerPoint-update-smart includes office 2011

### ISSUE THREAD

**Issue by karlmikaelskar** [autopkg/jss-recipes#22]
Hi!

I wanted to point out that this smart group will catch PowerPoint from office 2011 and thus always be true if Office 2011 is installed.

novaksam solved it like this:

Application Title is Microsoft PowerPoint.app
and Application Version like 15.
and Application Version is not <current version>
and Computer Group member of Testing
and Operating System like 10.10
or Operating System like 10.11

thanks for the recipes!

regards
Mikael Johansson

PS. Maybe this is applicable to all the other office applications. DS.

**Comment by sheagcraig** [comment]
Geez, I thought we had fixed that already. Apparently not!

**Comment by sheagcraig** [comment]
Can you check your recipes-
the current Office 2016 smart group criteria SHOULD be
```
Application Title is Microsoft %Whatever%.app
and Application Version is not %Current Version%
and Application Version is like 15.
and Computer Group member of Testing
```

**Comment by karlmikaelskar** [comment]
That is my smart group but is still includes office 2011. 

updated 20150910

<computer_group>
    <name>%group_name%</name>
    <is_smart>true</is_smart>
    <criteria>
        <criterion>
            <name>Application Title</name>
            <priority>0</priority>
            <and_or>and</and_or>
            <search_type>is</search_type>
            <value>%JSS_INVENTORY_NAME%</value>
        </criterion>
        <criterion>
            <name>Application Version</name>
            <priority>1</priority>
            <and_or>and</and_or>
            <search_type>is not</search_type>
            <value>%VERSION%</value>
        </criterion>
        <criterion>
            <name>Application Version</name>
            <priority>2</priority>
            <and_or>and</and_or>
            <search_type>like</search_type>
            <value>15.</value>
        </criterion>
        <criterion>
            <name>Computer Group</name>
            <priority>3</priority>
            <and_or>and</and_or>
            <search_type>member of</search_type>
            <value>Testing</value>
        </criterion>
    </criteria>
</computer_group>

**Comment by sheagcraig** [comment]
That's super weird. It works correctly on my JSS. @homebysix do you want to weigh in on this?

**Comment by homebysix** [comment]
Should be fixed for now by #23.

**Comment by sheagcraig** [comment]
So we just added that version like 15 thing... Is it possible that your JSS, while having the correct criteria, has not recalculated membership? I know (vaguely) that there's that bug where smart groups don't get recalculated membership under certain conditions.

**Comment by homebysix** [comment]
@karlmikaelskar, is this still happening for you after doing a `autopkg repo-update jss-recipes`?

**Comment by karlmikaelskar** [comment]
I has to remove the smart group and run the recipe again. Works now!

Thanks
/Mikael
