### ISSUE TITLE
request use Spotify full version numbers

### ISSUE THREAD

**Issue by Tafkaroll** [autopkg/jss-recipes#222]
Request for not splitting or removing parts of the version numbering in the Spotify recipe.

**Comment by homebysix** [comment]
Hi @Tafkaroll - You may want to open an issue on my homebysix-recipes repo instead, as it's the pkg recipe (parent of the jss recipe) that does the [version splitting](https://github.com/autopkg/homebysix-recipes/blob/master/Spotify/Spotify.pkg.recipe#L36).
