### ISSUE TITLE
Proposal for an additional CFBundleVersionSmartGroupTemplate.xml criterion

### ISSUE THREAD

**Issue by homebysix** [autopkg/jss-recipes#24]
Here's the current CFBundleVersionSmartGroupTemplate.xml:

```
<computer_group>
    <name>%group_name%</name>
    <is_smart>true</is_smart>
    <criteria>
        <criterion>
            <name>Application Title</name>
            <priority>0</priority>
            <and_or>and</and_or>
            <search_type>is</search_type>
            <value>%JSS_INVENTORY_NAME%</value>
        </criterion>
        <criterion>
            <name>%NAME%Version</name>
            <priority>1</priority>
            <and_or>and</and_or>
            <search_type>is not</search_type>
            <value>%VERSION%</value>
        </criterion>
        <criterion>
            <name>Computer Group</name>
            <priority>2</priority>
            <and_or>and</and_or>
            <search_type>member of</search_type>
            <value>Testing</value>
        </criterion>
    </criteria>
</computer_group>
```

I would propose adding one more criterion:

```
        <criterion>
            <name>%NAME%Version</name>
            <priority>3</priority>
            <and_or>and</and_or>
            <search_type>is not</search_type>
            <value></value>
        </criterion>
```

This would prevent computers from being scoped into the smart group if the %NAME%Version extension attribute has not yet been evaluated during a recon.

**Comment by sheagcraig** [comment]
That seems logical to me. Is that an issue? I have no experience with stuff
falling through like that.

**Comment by homebysix** [comment]
Well, the example I'm encountering today is this:

1. Run Slack.jss recipe for the first time.
2. Observe that ALL computers in the Testing group are scoped into Slack-update-smart, even the ones which already have the latest version of Slack.
3. As computers begin to run inventory (which can happen up to 24 hours later), the ones with the latest version of Slack are scoped out of the Slack-update-smart group.

So the proposal above eliminates the gap between 2 and 3.
