### ISSUE TITLE
Skitch failing autopkg

### ISSUE THREAD

**Issue by tsinghzf** [autopkg/jss-recipes#246]
Below is the error i am receiving, please make the fix

Installing Skitch
Processing Skitch.jss.recipe...
WARNING: Skitch.jss.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLDownloader
URLDownloader: File size returned by webserver matches that of the cached file: 5109 bytes
URLDownloader: WARNING: Matching a download by filesize is a fallback mechanism that does not guarantee that a build is unchanged.
URLDownloader: Using existing /Users/mluffy/Library/AutoPkg/Cache/com.github.jss-recipes.jss.Skitch/downloads/Skitch.zip
EndOfCheckPhase
Unarchiver
Unarchiver: Guessed archive format 'zip' from filename Skitch.zip
Unarchiving /Users/mluffy/Library/AutoPkg/Cache/com.github.jss-recipes.jss.Skitch/downloads/Skitch.zip with ditto failed: ditto: Couldn't read PKZip signature

Failed.
Receipt written to /Users/mluffy/Library/AutoPkg/Cache/com.github.jss-recipes.jss.Skitch/receipts/Skitch.jss-receipt-20210420-150600.plist

The following recipes failed:
    Skitch.jss.recipe
        Error in com.github.jss-recipes.jss.Skitch: Processor: Unarchiver: Error: Unarchiving /Users/mluffy/Library/AutoPkg/Cache/com.github.jss-recipes.jss.Skitch/downloads/Skitch.zip with ditto failed: ditto: Couldn't read PKZip signature

Nothing downloaded, packaged or imported.
Processing Skitch.jss.recipe...
WARNING: Skitch.jss.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLDownloader
URLDownloader: File size returned by webserver matches that of the cached file: 5109 bytes
URLDownloader: WARNING: Matching a download by filesize is a fallback mechanism that does not guarantee that a build is unchanged.
URLDownloader: Using existing /Users/mluffy/Library/AutoPkg/Cache/com.github.jss-recipes.jss.Skitch/downloads/Skitch.zip
EndOfCheckPhase
Unarchiver
Unarchiver: Guessed archive format 'zip' from filename Skitch.zip
Unarchiving /Users/mluffy/Library/AutoPkg/Cache/com.github.jss-recipes.jss.Skitch/downloads/Skitch.zip with ditto failed: ditto: Couldn't read PKZip signature

Failed.
Receipt written to /Users/mluffy/Library/AutoPkg/Cache/com.github.jss-recipes.jss.Skitch/receipts/Skitch.jss-receipt-20210420-150605.plist

The following recipes failed:
    Skitch.jss.recipe
        Error in com.github.jss-recipes.jss.Skitch: Processor: Unarchiver: Error: Unarchiving /Users/mluffy/Library/AutoPkg/Cache/com.github.jss-recipes.jss.Skitch/downloads/Skitch.zip with ditto failed: ditto: Couldn't read PKZip signature

**Comment by homebysix** [comment]
Hello @tsinghzf - It looks like the error is occurring in the `Unarchiver` processor, which isn't in the jss recipe. I'd recommend following the trail of parent recipes until you find which recipe contains `Unarchiver`, then opening an issue on that recipe's repository. Thanks!
