### ISSUE TITLE
Zoom updates have been separated for m1 and intel

### ISSUE THREAD

**Issue by tsinghzf** [autopkg/jss-recipes#263]
https://zoom.us/download

Zoom Client for Meetings has been set up by the vendor to be separate for lintels and m1s.

Can you please update recipes to accommodate for this?

**Comment by homebysix** [comment]
The upstream issue would need to be addressed first: https://github.com/autopkg/hansen-m-recipes/issues/210

**Comment by homebysix** [comment]
Closed upstream — unnecessary due to Zoom's IT Installer being Universal.
