### ISSUE TITLE
validate_recipes.py needs to be updated to account for Office 2016 recipes

### ISSUE THREAD

**Issue by homebysix** [autopkg/jss-recipes#32]
Currently, the Office 2016 recipes don't validate, because of necessary changes that were made to them.

```
--------------------------------------------------------------
 Testing recipe: ./Microsoft Excel/Microsoft Excel.jss.recipe 
--------------------------------------------------------------
Test: Parent Recipe is in AutoPkg org. Result: False
Test: Recipe has only a single processor, of type 'JSSImporter'. (Too many processors: 4 > 1) Result: False
Test: GROUP_TEMPLATE is 'SmartGroupTemplate.xml'. Result: False
```

Or maybe validate_recipes.py could be like pylint and we could put a comment in the recipe giving it certain waivers:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>ValidationNotes</key>
    <string>IGNORE:ParentRecipe,SingleProcessor,GroupTemplate</string>
[...]
```

Just spitballing...

**Comment by sheagcraig** [comment]
Yeah-the validator is a bit rough at the moment. It's not capable of handling certain kinds of deviations.

I'd say the idea of a kind of pragma key in the recipes would be a good way to allow the validator to handle it, but then what's to stop recipe authors just putting in a bunch of pragma marks to ignore all of things they don't agree with? Moving forward, it would be nice to have this repo perform a complete validator run against all of the recipes on an update hook and display the status of that validation. But we would have to handle the exceptions somehow. Maybe an exceptions file of some kind-a plist (more plists, everywhere!) that had a dictionary of recipes, and exemptions (we could create a code for each validation type).

**Comment by homebysix** [comment]
Closing issue due to [repo deprecation and archive](https://github.com/autopkg/jss-recipes/issues/267).
