### ISSUE TITLE
Silverlight.jss cannot read info.plist

### ISSUE THREAD

**Issue by rougegoat** [autopkg/jss-recipes#40]
When you run the Silverlight.jss recipe, it will always error out saying something along the lines of:

```
Error running recipes
File '<cache directory>/com.github.jss-recipes.jss.Silverlight/unpack/Internet Plug-Ins/Silverlight.plugin/Contents/Info.plist' does not exist or could not be read.
```

The Info.plist both exists and can be read by all users.  The recipe itself works just fine and uploads the file as expected.  It just always sends an error code along with it.

**Comment by rougegoat** [comment]
Nevermind.  Just ran the parent recipe "Silverlight.pkg" from "com.github.autopkg" and it had the exact same error.  So it's not an issue with the Silverlight.jss recipe.  It's an issue with the parent recipe to it.

**Comment by sheagcraig** [comment]
@rougegoat I would hazard to guess that while `unpack/Internet Plug-Ins/Silverlight.plugin/Contents/Info.plist` exists, probably `<cache directory>/com.github.jss-recipes.jss.Silverlight/unpack/Internet Plug-Ins/Silverlight.plugin/Contents/Info.plist` does not. It seems like the cache_directory variable is not getting expanded.

**Comment by rougegoat** [comment]
For the record, I replaced the full path(which fills in correctly) with that <cache directory> bit.   The path has personal info in it, so better safe than sorry.

**Comment by sheagcraig** [comment]
Ah, got it!
