### ISSUE TITLE
Adobe Acrobat Reader DC

### ISSUE THREAD

**Issue by rrwitt** [autopkg/jss-recipes#48]
Does not pull the right app in the Smart Group missing "Acrobat" in the title
Same app does not pull in version number either

Is this the right spot to mention these?

Thanks
Ryan

**Comment by homebysix** [comment]
This is the right place! I'll look into it.

**Comment by homebysix** [comment]
This should be fixed by https://github.com/autopkg/recipes/commit/372b65ed55ec5077fb0ebe70f3da2d4115e57670.
