### ISSUE TITLE
Perhaps we can't have spaces in the names...

### ISSUE THREAD

**Issue by novaksam** [autopkg/jss-recipes#5]
I've been working on converting my repo to the standard shown here and I encountered an issues where if I have a recipe with spaces in the name (ex. Adobe DNG Converter.jss.recipe from this repo) and you make an override of it (I use Autopkgr, but the same thing happens using autopkg from the command line) it adds spaces into identifier of the override recipe.

Example:
Source Recipe identifier
> com.github.jss-recipes.jss.AdobeDNGConverter

Override Recipe identifier
> local.jss.Adobe DNG Converter

**Comment by gregneagle** [comment]
That's a perfectly valid identifier, even if it might be cumbersome to work with

**Comment by novaksam** [comment]
Ah, just had to escape the spaces.

In keeping with the theme of consistency throughout the packaging process, wouldn't it make sense for the overridden recipe to match the 'style' of the recipe from the parent? Though I suppose that's an issue for the main autopkg repo...

**Comment by sheagcraig** [comment]
I think that's probably an upstream issue with autopkg, and I think that since it's a valid identifier, that's probably how it's supposed to work.

**Comment by gregneagle** [comment]
Identifiers are arbitrary strings. When 'automagically" creating an identifier for a recipe override we had two choices: "local." + something derived from the filename or "local." + the parent recipe identifier. I worried that might lead to "local.local.local.local.org.foo.pkg,bar" identifiers, so I chose the former.
