### ISSUE TITLE
GoogleChrome.jss — "Error the package path specified was invalid"

### ISSUE THREAD

**Issue by aa-it-autopkg** [autopkg/jss-recipes#52]
After running this jss recipe, it actually imported all the info onto jss, but only chrome pkg installation failed.  it gave an error "Error the package path specified was invalid" '/Library/Application Support/JAMF/Downloads/Google Chrome-48.0.2564.116.pkg'. " on JSS

For other jss recipe, i've tested with no issue and installed successfully.

**Comment by homebysix** [comment]
Hi @aa-it-autopkg — Is this still happening for you with the latest version of Chrome?

What happens if you run `autopkg run -v com.github.autopkg.pkg.googlechrome`, and then upload the resulting pkg file to your JSS and deploy it to a test Mac? Do you get the same error?
