### ISSUE TITLE
Adobe Reader (non DC) does not have versioning

### ISSUE THREAD

**Issue by rrwitt** [autopkg/jss-recipes#54]
The current JSS policy for Adobe Reader non DC does not have a version coming in from the package.  Without versioning it does not know to update the package.  Is this something that someone with a little more experience than me can look into. 

Thanks
Ryan

**Comment by rrwitt** [comment]
![screen shot 2016-03-01 at 1 11 25 pm](https://cloud.githubusercontent.com/assets/9356999/13438610/4ff2623a-dfaf-11e5-8bdd-d605ea47dd72.png)

I am seeing a lot of stuff about versioners on the MacAdmins Slack channel.

**Comment by homebysix** [comment]
Yes, this is a known issue that https://github.com/autopkg/jss-recipes/pull/51 attempts to resolve. But it should really be resolved upstream if possible.

**Comment by homebysix** [comment]
Resolved in https://github.com/autopkg/recipes/pull/138.
