### ISSUE TITLE
Sketch.jss.recipe downloads old version

### ISSUE THREAD

**Issue by lucascantor** [autopkg/jss-recipes#71]
Sketch.jss.recipe downloads Sketch version 3.5 but the current version is 3.7.2

The string value for the MinimumVersion key is 0.5.0 in [Sketch.jss.recipe](https://github.com/autopkg/jss-recipes/blob/master/Sketch/Sketch.jss.recipe) and 0.6.0 in the [parent recipe](https://github.com/autopkg/homebysix-recipes/blob/a028b6094ef791277a7af23f0bb0d149107f1ce1/BohemianCoding/Sketch.download.recipe), though editing my override to 0.6.0 or higher doesn't seem to have any effect.

**Comment by homebysix** [comment]
Thanks for reporting this! Should be fixed by https://github.com/autopkg/homebysix-recipes/pull/62.
