### ISSUE TITLE
Silverlight JSS recipe gives Version Error

### ISSUE THREAD

**Issue by opel70** [autopkg/jss-recipes#73]
When running the Silverlight.jss recipe (via Autopkgr or Autopkg in Terminal) I get the error: JSSImporter requires missing argument version.

I did manually create an Override with the blank version key. I am wondering why this became an issue recently.

**Comment by homebysix** [comment]
Thanks for reporting this. Although the `%version%` is floating around in the environment by the time JSSImporter runs, it may be that the explicit presence of the `<key>version</key>` in the JSSImporter arguments will prevent this from happening. I've made that change in the repository.
