### ISSUE TITLE
Adobe Acrobat Reader DC.jss is creating a corrupted pkg

### ISSUE THREAD

**Issue by dnikles** [autopkg/jss-recipes#74]
The dmg it downloads is good, and the .pkg is creates is good, but then it converts it to another .pkg which is bad. I get 2 .pkg files, AcroRdrDC_1501620039_MUI.pkg which is good, Adobe Acrobat Reader DC-15.016.20039.pkg which is bad. 
![acroerror](https://cloud.githubusercontent.com/assets/17789455/15611241/71816d42-23f7-11e6-8cc0-74f0ebd21495.png)

**Comment by homebysix** [comment]
Good catch, thank you!
