### ISSUE TITLE
com.github.jss-recipes.jss.OracleJava8JDK (or a parent) needs updated URL

### ISSUE THREAD

**Issue by everetteallen** [autopkg/jss-recipes#88]
8/19/16 11:02:10.928 AM AutoPkgr[85839]: Run status: Processing com.github.jss-recipes.jss.OracleJava8JDK...
8/19/16 11:02:10.928 AM AutoPkgr[85839]: Processing com.github.jss-recipes.jss.OracleJava8JDK...
8/19/16 11:03:06.745 AM AutoPkgr[85839]: [DEBUG] Found app and version: Oracle Java 8 JDK:1.8.0
8/19/16 11:03:56.359 AM AutoPkgr[85839]: Error [1] Error running recipes 
 Response Code: 404 Response: Not Found. The server has not found anything matching the request URI
8/19/16 11:05:56.254 AM AutoPkgr[85839]: [DEBUG] Completed AutoPkg Task:
  /usr/bin/python /usr/local/bin/autopkg run com.github.jss-recipes.jss.OracleJava8JDK --report-plist /var/folders/jh/8001rxgs1x50k8y9c475qhsw0000gp/T/com.lindegroup.AutoPkgr/20160819110210 -v

**Comment by homebysix** [comment]
@everetteallen: The OracleJava8JDK recipe is working well for me. It's possible a change was made to a parent recipe recently. Can you try it again?

**Comment by patgmac** [comment]
This recipe has been working well for me as well.
